spring:
  mail:
    host: smtp.naver.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    property:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
#      mail.smtp.ssl.trust: smtp.naver.com
      mail.smtp.starttls.enable: true
